services:
  db:
    image: postgres:15
    container_name: lms_db
    environment:
      POSTGRES_DB: KyrsovayaBD
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - lms-db-data:/var/lib/postgresql/data

volumes:
  lms-db-data:
